export  class Order{
    constructor (city,
        street,
        state,
        country,
        zipcode,
        cardnumber,
        cardexpiratio,
        expiration,
        cardsecuritynumber,
        cardholdername,
        cardtypeid,
        buyer,
        ordernumber,
        total,
        orderItems){
            this.street=street
            this.state=state
            this.country=country
            this.zipcode=zipcode
            this.cardnumber=cardnumber
            this.cardexpiratio=cardexpiratio
            this.expiration=expiration
            this.cardsecuritynumber=cardsecuritynumber
            this.cardholdername=cardholdername
            this.cardtypeid=cardtypeid
            this.buyer=buyer
            this.ordernumber=ordernumber
            this.total=total
            this.orderItems=orderItems
        }
}